# Generated by Django 2.2.2 on 2020-10-14 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20201014_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
