# Generated by Django 2.2.2 on 2020-10-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_training_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('descript', models.TextField(max_length=500)),
                ('repetition', models.PositiveIntegerField()),
                ('duration', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.AddField(
            model_name='training',
            name='exercise',
            field=models.ManyToManyField(to='data.Exercise'),
        ),
    ]
